config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
    root 'groups#index', as: :authenticated_root
  end

  unauthenticated do
    root 'groups#splash', as: :unauthenticated_root
  end

  resources :groups do
    resources :transfers
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :manage, :all, user:
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'author_id'
  has_many :transfer_groups
  has_many :transfers, through: :transfer_groups
  has_one_attached :icon

  validates :name, presence: true, length: { in: 1..100 }
  validate :icon_is_image

  def total_tranfers
    transfers.sum(:amount)
  end

  private

  def icon_is_image
    if icon.attached? && !icon.image?
      errors.add(:icon, 'must be an image')
    elsif !icon.attached?
      errors.add(:icon, 'must be attached')
    end
  end
end

app/models/transfer.rb
class Transfer < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'author_id'
  has_many :transfer_groups
  has_many :groups, through: :transfer_groups

  validates :name, presence: true
  validates :amount, numericality: { greater_than_or_equal_to: 0 }, presence: true
end

app/models/transfer_group.rb
class TransferGroup < ApplicationRecord
  belongs_to :transfer
  belongs_to :group
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :groups, class_name: 'Group', foreign_key: 'author_id'
  has_many :transfers, class_name: 'Transfer', foreign_key: 'author_id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?
  before_action :authenticate_user!, except: [:splash]

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :current_password)
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[show edit update destroy]

  def index
    @groups = current_user.groups.includes(:user, :icon_attachment).all.preload(icon_attachment: :blob)
  end

  def show
    group = Group.find(params[:id])
    @transfers = group.transfers.order(created_at: :desc)
  end

  def new
    @group = Group.new
  end

  def edit; end

  def splash; end

  def create
    @group = Group.new(group_params)
    @group.user = current_user

    respond_to do |format|
      if @group.save
        format.html { redirect_to authenticated_root_path, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to group_url(@group), notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:name, :icon, :user_id)
  end
end

app/controllers/transfers_controller.rb
class TransfersController < ApplicationController
  # before_action :set_transfer, only: %i[show edit create update destroy]

  # GET /transfers or /transfers.json
  def index
    @transfers = Transfer.all
  end

  # GET /transfers/1 or /transfers/1.json
  def show; end

  # GET /transfers/new
  def new
    @transfer = Transfer.new
    @group = Group.find(params[:group_id])
  end

  # GET /transfers/1/edit
  def edit; end

  # POST /transfers or /transfers.json
  def create
    @group = Group.find(params[:transfer][:selected_group_id])
    @transfer = @group.transfers.new(transfer_params)
    @transfer.user = current_user

    respond_to do |format|
      if @transfer.save
        TransferGroup.create(group: @group, transfer: @transfer)
        format.html { redirect_to group_path(@group), notice: 'Transfer was successfully created.' }
        format.json { render :show, status: :created, location: @transfer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @transfer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transfers/1 or /transfers/1.json
  def update
    respond_to do |format|
      if @transfer.update(transfer_params)
        format.html { redirect_to transfer_url(@transfer), notice: 'Transfer was successfully updated.' }
        format.json { render :show, status: :ok, location: @transfer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @transfer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transfers/1 or /transfers/1.json
  def destroy
    @transfer.destroy

    respond_to do |format|
      format.html { redirect_to transfers_url, notice: 'Transfer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_transfer
    @transfer = Transfer.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def transfer_params
    params.require(:transfer).permit(:name, :amount, :author_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/transfers_helper.rb
module TransfersHelper
end

app/views/groups/_form.html.erb
<%= form_with(model: group) do |form| %>
  <% if group.errors.any? %>
    <div class="text-red-500">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>
      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="mt-4">
    <%= form.text_field :name, placeholder: "Name", class: "w-full px-4 py-2 border" %>
  </div>
  <div class="mt-4">
    <%= form.label :icon, "Choose an icon(must be an image type)", style: "display: block",class: "text-gray-400"  %>
    <%= form.file_field :icon, class: "w-full px-4 py-2 border" %>
  </div>
  <div class="mt-4">
    <%= form.submit "Save", class: "px-4 py-2 w-[50%] bg-main text-white p-3 rounded-[4px] text-center text-white cursor-pointer" %>
  </div>
<% end %>

app/views/groups/_group.html.erb
<li id="<%= dom_id group %>" class="list-unstyled">
  <div class="row align-items-center mb-3 py-2 border border-1 mx-3">
    <span class="col-3">
      <% if group.icon.attached? %>
        <%= image_tag(group.icon, class: "w-[60px] h-[60px]", alt: "#{group.name}") %>
      <% end %>
    </span>
    <span class="col-6 text-gray-600">
      <%= group.name %>
    </span>
    <span class="col-3 font-bold text-text_color">$<%= group.total_tranfers %></span>
  </div>
</li>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render "form", group: @group %>

<br>

<div>
  <%= link_to "Show this group", @group %> |
  <%= link_to "Back to groups", groups_path %>
</div>

app/views/groups/index.html.erb
<div id="groups" class="mb-[90px] mt-3">
  <% if @groups.empty? %>
    <p class="text-center">No categories yet.</p>
  <% else %>
    <% @groups.each do |group| %>
      <% if can? :read, group %>
        <a href="<%= group_path(id: group) %>" class="text-decoration-none text-black">
          <%= render group %>
        </a>
      <% end %>
    <% end %>
  <% end %>
</div>
<div class="bg-main fixed bottom-0 w-full">
  <a href="<%= new_group_path %>" id="new-group-btn" class="block no-underline border border-white text-xl text-white p-3 m-3 rounded-[4px] text-center">New Category</a>
</div>

app/views/groups/new.html.erb
<%= render "form", group: @group %>

<br>

<div class="hidden">
  <%= link_to "Back to groups", groups_path %>
</div>

app/views/groups/show.html.erb
<section class="mt-3">
  <%= render @group %>
  <div class="px-3 mb-[90px]">
    <table class="w-full box-border">
      <thead>
        <tr>
          <th class="text-center border p-2">
            Name
          </th>
          <th class="text-center border p-2">
            Amount
          </th>
        </tr>
      </thead>
      <tbody>
        <% if @transfers.any? %>
          <% @transfers.each do |transfer| %>
            <tr>
              <td class="text-center border text-gray-600 p-1"><%= transfer.name %></td>
              <td class="text-center border text-text_color font-semibold p-1">$<%= transfer.amount %></td>
            </tr>
          <% end %>
        <% else %>
          <tr>
            <td colspan="2" class="text-center border text-gray-600 p-1">No transfers yet.</td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="hidden">
    <%= link_to "Edit this group", edit_group_path(@group) %> |
    <%= link_to "Back to groups", groups_path %>
    <%= button_to "Destroy this group", @group, method: :delete %>
  </div>
  <div class="bg-main fixed bottom-0 w-full">
    <a href="<%= new_group_transfer_path(@group) %>" id='new-transfer-btn' class="block no-underline border border-white text-white p-3 text-xl m-3 rounded-[4px] text-center">New Transation</a>
  </div>
</section>

app/views/groups/splash.html.erb
<div class="h-screen flex flex-col box-border">
  <div class="flex items-center justify-center h-[90%]">
    <h1 class="font-bold text-5xl italic">
      BudgetBuddy
    </h1>
  </div>
  <div class="flex flex-col mt-auto w-full">
    <a href="<%= new_user_session_path %>" class="bg-second text-white no-underline p-4 text-center text-2xl">Log In</a>
    <a href="<%= new_user_registration_path %>" class="text-text_color no-underline p-4 text-center text-2xl">Sign Up</a>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetBuddy</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
  </head>
  <body>
    <% unless request.path == '/' && !user_signed_in? %>
      <%= render partial: 'shared/navbar' %>
    <% end %>
    <%= render partial: 'shared/flash' %>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success alert-dismissible fade show mb-0" role="alert">
    <%= flash[:notice] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>
<% if flash[:alert] %>
  <div class="alert alert-warning alert-dismissible fade show mb-0" role="alert">
    <%= flash[:alert] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-second">
  <div class="container-fluid d-flex justify-content-between">
    <% if request.path == '/users/sign_in' %>
      <div class="custom-w flex justify-content-center">
        <h2 class="text-white mb-0 ">Log In</h2>
      </div>
    <% elsif request.path == '/users/sign_up' %>
      <div class="custom-w flex justify-content-center">
        <h2 class="text-white mb-0 ">Sign Up</h2>
      </div>
    <% end %>
    <% if request.path == '/groups/new' || request.path.match?(/^\/groups\/\d+\/transfers\/new$/) || request.path.match?(/^\/groups\/\d+$/) %>
      <a href="<%= authenticated_root_path %>">
        <i class="bi bi-arrow-left text-white text-xl" style="font-size: 1.8rem;"></i>
      </a>
    <% end %>
    <% if request.path == '/' %>
      <div class="custom-w flex justify-content-center">
        <h2 class="text-white mb-0 ">Categories</h2>
      </div>
    <% elsif request.path.match?(/^\/groups\/\d+$/) %>
      <div>
        <h2 class="text-white mb-0">Transactions</h2>
      </div>
    <% end %>
    <button class="navbar-toggler bg-white" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active text-white" aria-current="page" href="<%= authenticated_root_path %>">Home</a>
        </li>
        <li class="nav-item">
          <% if user_signed_in? %>
            <%= button_to "Log out", destroy_user_session_path, method: "delete", class: "nav-link active text-white" %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/transfers/_form.html.erb
<%= form_with(model: transfer, url: group_transfers_path(@group)) do |form| %>
  <% if transfer.errors.any? %>
    <div class="text-red-500">
      <h2><%= pluralize(transfer.errors.count, "error") %> prohibited this transfer from being saved:</h2>
      <ul>
        <% transfer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="mt-4">
    <%= form.text_field :name, placeholder: "Name", class: "w-full px-4 py-2 border", required: true %>
  </div>
  <div class="mt-4">
    <%= form.number_field :amount, placeholder: "Amount", class: "w-full px-4 py-2 border", required: true %>
  </div>
  <div class="mt-4">
    <%= form.collection_select(:selected_group_id, Group.where(author_id: current_user.id), :id, :name, { include_blank: 'Select Category' }, { class: 'form-select', id: 'group-select', required: true }) %>
  </div>
  <div class="mt-4">
    <%= form.submit "Save", class: "px-4 py-2 bg-main text-white rounded-[4px] w-[50%] cursor-pointer" %>
  </div>
<% end %>

app/views/transfers/_transfer.html.erb
<div id="<%= dom_id transfer %>">
  <p>
    <strong>Name:</strong>
    <%= transfer.name %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= transfer.amount %>
  </p>

  <p>
    <strong>User:</strong>
    <%= transfer.user_id %>
  </p>

</div>

app/views/transfers/edit.html.erb
<h1>Editing transfer</h1>

<%= render "form", transfer: @transfer %>

<br>

<div>
  <%= link_to "Show this transfer", @transfer %> |
  <%= link_to "Back to transfers", transfers_path %>
</div>

app/views/transfers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Transfers</h1>

<div id="transfers">
  <% @transfers.each do |transfer| %>
    <%= render transfer %>
    <p>
      <%= link_to "Show this transfer", transfer %>
    </p>
  <% end %>
</div>

<%= link_to "New transfer", new_transfer_path %>

app/views/transfers/new.html.erb
<%= render "form", transfer: @transfer, group: @group %>

<br>

<div class="hidden">
  <%= link_to "Back to transfers", group_transfers_path(@group) %>
</div>

app/views/transfers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @transfer %>

<div>
  <%= link_to "Edit this transfer", edit_transfer_path(@transfer) %> |
  <%= link_to "Back to transfers", transfers_path %>

  <%= button_to "Destroy this transfer", @transfer, method: :delete %>
</div>